name: Github wf test
on: [push]
jobs:
  text-action:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: |
          echo "inside action step"
      - name: test2
        run: |
          pwd
          echo "${{ github.workspace }}"
          ls ${{ github.workspace }}
