name: Github wf test
on: [push]
jobs:
  text-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test1
        run: |
          echo "inside action step"
      - name: test2
        run: |
          pwd
          echo "${{ github.workspace }}"
          ls ${{ github.workspace }}
          ./test.sh
      - name: login to gh container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
      - name: build image
        run: |
          docker build \
            . \
            --tag ghcr.io/aloyr/hello-docker-gcr-demo:latest \
            --label "org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}" \
            --label "org.opencontainers.image.description=Github docker test" \
            --label "org.opencontainers.image.licenses=MIT"
          docker push ghcr.io/aloyr/hello-docker-gcr-demo:latest
